### ISSUE TITLE
Side Screen Overflow for longer names

### ISSUE THREAD

**Issue by anand-aman** [ankay212000/News_app_2.0#10]
![Screenshot_20200623-232520](https://user-images.githubusercontent.com/54910807/85440301-83977e00-b5ab-11ea-943b-24790c05b47a.png)

**Comment by ankay212000** [comment]
I guess i've missed using MediaQuery here you can use to resolve this issue,you can work on this.

**Comment by ankay212000** [comment]
hi @anand-aman  are you working on this or on any other issue?

**Comment by anand-aman** [comment]
I'll start working on this issue.
