### ISSUE TITLE
Bottom Navigation Bar missing

### ISSUE THREAD

**Issue by ankay212000** [ankay212000/News_app_2.0#2]
Add bottom navigation bar to navigate to them e.g. User page

**Comment by tanvibattu** [comment]
Can i work on this issue?

**Comment by ankay212000** [comment]
Just tell me what are things you will add on navigation bar or if you want my suggestion then I'll say: 
(i) bookmarked page where all bookmarked pages are visible
(ii) user page where his bio,about,name,circular dp(for now any avatar will do the work).
(iii) Shared news history 

Reply me after if you have more or a different ideas, we'll discuss and then I'll assign you this issue

**Comment by ankay212000** [comment]
> Can i work on this issue?

Just tell me what are things you will add on navigation bar or if you want my suggestion then I'll say:
(i) bookmarked page where all bookmarked pages are visible
(ii) user page where his bio,about,name,circular dp(for now any avatar will do the work).
(iii) Shared news history

Reply me after if you have more or a different ideas, we'll discuss and then I'll assign you this issue

**Comment by tanvibattu** [comment]
Yes apart from these pages we can add trending news page in the bottom navigation bar. 
Further we can add a top navigation bar in the news feed page where we can have different tabs for entertainment,sports,international news etc.

**Comment by tanvibattu** [comment]
> > Can i work on this issue?
> 
> Just tell me what are things you will add on navigation bar or if you want my suggestion then I'll say:
> (i) bookmarked page where all bookmarked pages are visible
> (ii) user page where his bio,about,name,circular dp(for now any avatar will do the work).
> (iii) Shared news history
> 
> Reply me after if you have more or a different ideas, we'll discuss and then I'll assign you this issue

Yes apart from these pages we can add trending news page in the bottom navigation bar.
Further we can add a top navigation bar in the news feed page where we can have different tabs for entertainment,sports,international news etc.

**Comment by ankay212000** [comment]
> > > Can i work on this issue?
> > 
> > 
> > Just tell me what are things you will add on navigation bar or if you want my suggestion then I'll say:
> > (i) bookmarked page where all bookmarked pages are visible
> > (ii) user page where his bio,about,name,circular dp(for now any avatar will do the work).
> > (iii) Shared news history
> > Reply me after if you have more or a different ideas, we'll discuss and then I'll assign you this issue
> 
> Yes apart from these pages we can add trending news page in the bottom navigation bar.
> Further we can add a top navigation bar in the news feed page where we can have different tabs for entertainment,sports,international news etc.

if you can implement this then it will be very important contribution, you can work on this issue,I'll assign you this issue

**Comment by ankay212000** [comment]
But if anybody wants to work on this issue can also work by communicating on with each other
