### ISSUE TITLE
PART 1: Bookmark functionality and navigation should be done by bottom navigation bar

### ISSUE THREAD

**Issue by ankay212000** [ankay212000/News_app_2.0#3]
Add like and bookmark functionality and a snackbar along with storing it on firebase

**Comment by anand-aman** [comment]
Now I would like to work on this issue.

**Comment by anand-aman** [comment]
Plz assign this issue

**Comment by anand-aman** [comment]
This issue has been fixed.

**Comment by ankay212000** [comment]
> This issue has been f
