### ISSUE TITLE
More appealing Login and Registration page using flutter animation

### ISSUE THREAD

**Issue by ankay212000** [ankay212000/News_app_2.0#5]

**Comment by Pranjal-Jayaswal** [comment]
May i work on this ?

**Comment by ankay212000** [comment]
Sure, but i'll assign you this after resolving the #8  issue which is assigned to you. If you have already started to work on this issue then i'll assign you this,but after then you have to resolve the #8, then only you will get next job

**Comment by Pranjal-Jayaswal** [comment]
i have already completed the #8 issue and will add the pull request soon...and if u allow then i will start my work on this

**Comment by ankay212000** [comment]
Sure you can work on this but design the login page such that the original theme of app is maintained

**Comment by Pranjal-Jayaswal** [comment]
Okay
