### ISSUE TITLE
Authenticating Spinner on the Login Screen

### ISSUE THREAD

**Issue by anand-aman** [ankay212000/News_app_2.0#7]
Example: 
https://sourcey.com/beautiful-android-logn-and-signup-screens-with-material-design/screenshot-login-spinner.png

**Comment by ankay212000** [comment]
> Example:
> https://sourcey.com/beautiful-android-logn-and-signup-screens-with-material-design/screenshot-login-spinner.png

Yes buddy this will work perfectly
and if completed this work it will also clear the bug, #1

**Comment by ankay212000** [comment]
I've assigned you this issue
