### ISSUE TITLE
Screen Size Overflow on Splashscreen page

### ISSUE THREAD

**Issue by Pranjal-Jayaswal** [ankay212000/News_app_2.0#8]
There is a screen overflow on my physical device on  Splashscreen  page.

![Splash screen](https://user-images.githubusercontent.com/63522945/85429592-935b9600-b59c-11ea-91e2-b816029e4a56.jpeg)

**Comment by Pranjal-Jayaswal** [comment]
Can i work on this?

**Comment by Pranjal-Jayaswal** [comment]
May i work on this?

**Comment by ankay212000** [comment]
> May i work on this?

Yes you can, I don't know why this is happening I have used MediaQuery.... But let it be you can work upon this.
